---
title: "Lab 5"
author: "JP"
date: "11/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)

full_train <- read_csv("data/train.csv",
                       col_types = cols(.default = col_guess(), 
                        calc_admn_cd = col_character()))  %>% 
              select(-classification)
```

```{r}
# join first

set.seed(3000)
d <- d %>% sample_frac(.1)
```

```{r}
set.seed(3000)


(d_split <- initial_split(d)) 

d_train <- training(d_split)
d_test  <- testing(d_split)
```

```{r}
rec_yoself <- recipe(score ~ .,data = d_train) %>%
    step_mutate(tst_dt = lubridate::mdy_hms(tst_dt)) %>%
      update_role(contains("id"), ncessch, new_role = "id vars") %>%
    step_unknown(all_nominal()) %>% 
    step_novel(all_nominal()) %>% 
    step_dummy(all_nominal()) %>% 
    step_nzv(all_predictors()) %>%
    #step_mutate(z_rlprop = log(rl_prop),
    #           z_flprop = log(fl_prop)) %>% 
    #step_rm(fl_prop, rl_prop) %>% #remove potentially redundant variables
    step_normalize(rl_prop, fl_prop, teachers) %>%
    step_medianimpute(all_numeric(), -all_outcomes(), -has_role("id vars")) %>% #medianimpute only proportion variables 
    step_interact(terms = ~lat:lon)

```

```{r}
library(rpart)

simple_tree <- decision_tree() %>% 
  set_mode("classification") %>% 
  set_engine("rpart") %>% 
  set_args(cost_complexity = 0.01, min_n = 5)

m01 <- fit(mod_random1, accuracy_group ~ ., prep(rec) %>%  bake(train))
acc_check <- tibble(
    truth = prep(rec) %>%  bake(train) %>%  pull(accuracy_group),
    estimate = predict(m01$fit, type = "class")
  )
accuracy(acc_check, truth, estimate)
```


```{r}
library(baguette)
okay_trees <- bag_tree() %>% 
  set_mode("classification") %>% 
  set_args(cost_complexity = 0, min_n = 2) %>% 
  set_engine("rpart", times = 50) 
```

```{r}
set.seed(3000)

(cores <- parallel::detectCores())

now_those_r_trees <- rand_forest() %>%
set_engine("rpart",
num.threads = cores, #argument from {ranger}
importance = "permutation", #argument from {ranger}
verbose = TRUE) %>% #argument from {ranger}
set_mode("regression")

werkflo <- workflow() %>%
add_recipe(rec_yoself) %>%
add_model(model_of_forests)
```

