---
title: "AUCs"
author: "Shaina Trevino, Akhila Nekkanti, & Jonathan Pedroza"
date: "11/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
```

## Preliminary Model Fit

```{r st fit1 auc}

prelim_st <- readRDS(here::here("models", "fit1-st.Rds"))
show_best(prelim_st, metric = "roc_auc", n = 5) 

```

```{r jp fit1 auc}

prelim_jp <- readRDS(here::here("models", "fit1jp.Rds"))
show_best(prelim_jp, metric = "roc_auc", n = 5) 

```

```{r an fit1 auc}

prelim_an <- readRDS(here::here("models", "fit1an.Rds"))
show_best(prelim_an, metric = "roc_auc", n = 5) 


```

```{r finalfit}

knn_better <- readRDS(here::here("models", "knn2_fit.Rds"))
show_best(knn_better, metric = "roc_auc", n = 5) 


knn_best <- knn2_fit %>%
  select_best(metric = "roc_auc") 

# Finalize your model using the best tuning parameters
knn_mod_final <- knn2_mod %>%
  finalize_model(knn_best)

# Finalize your recipe using the best turning parameters
knn_rec_final <- knn2_fit %>%
  finalize_recipe(knn_best)

```

